# Generated by Django 4.0.4 on 2022-06-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tres_son_multitud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='caracteristicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comidas', models.CharField(max_length=40)),
                ('colores', models.CharField(max_length=40)),
                ('signo', models.CharField(max_length=40)),
                ('estatura', models.IntegerField()),
                ('peso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secundario', models.CharField(max_length=40)),
                ('tecnico', models.CharField(max_length=40)),
                ('licenciatura', models.CharField(max_length=40)),
                ('postgrado', models.CharField(max_length=40)),
                ('maestria', models.CharField(max_length=40)),
                ('doctorado', models.CharField(max_length=40)),
            ],
        ),
    ]
